version: '3.8'

services:
  db:
    image: mysql:8.0.38
    container_name: crud_exercise_db
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'crud_exercise_db'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: